/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.muhariananda.simplelaundry;

import id.muhariananda.simplelaundry.controller.IncomeController;
import id.muhariananda.simplelaundry.controller.OrderController;
import id.muhariananda.simplelaundry.controller.ServiceController;
import id.muhariananda.simplelaundry.service.OrderService;
import id.muhariananda.simplelaundry.service.ServiceService;
import id.muhariananda.simplelaundry.view.IncomePanelView;
import id.muhariananda.simplelaundry.view.OrderPanelView;
import id.muhariananda.simplelaundry.view.ServicePanelView;

/**
 *
 * @author muhariananda
 */
public class HomeLaundryFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeLaundryFrame
     *
     * @param orderPanel
     * @param servicePanel
     */
    public HomeLaundryFrame(OrderPanelView orderPanel, ServicePanelView servicePanel, IncomePanelView incomePanel) {
        initComponents();

        menuTab.addTab(null, orderPanel);
        menuTab.addTab(null, servicePanel);

        menuTab.addTab(null, incomePanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        orderMenuButton = new javax.swing.JButton();
        serviceMenuButton = new javax.swing.JButton();
        reportMenuButton = new javax.swing.JButton();
        menuTab = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu");
        jLabel1.setToolTipText("");

        orderMenuButton.setText("Pesanan");
        orderMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderMenuButtonActionPerformed(evt);
            }
        });

        serviceMenuButton.setText("Layanan");
        serviceMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceMenuButtonActionPerformed(evt);
            }
        });

        reportMenuButton.setText("Laporan");
        reportMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(serviceMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reportMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(orderMenuButton)
                .addGap(18, 18, 18)
                .addComponent(serviceMenuButton)
                .addGap(18, 18, 18)
                .addComponent(reportMenuButton)
                .addContainerGap(360, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuTab)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuTab)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serviceMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceMenuButtonActionPerformed
        menuTab.setSelectedIndex(1);
    }//GEN-LAST:event_serviceMenuButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowActivated

    private void orderMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderMenuButtonActionPerformed
        menuTab.setSelectedIndex(0);
    }//GEN-LAST:event_orderMenuButtonActionPerformed

    private void reportMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportMenuButtonActionPerformed
        menuTab.setSelectedIndex(2);
    }//GEN-LAST:event_reportMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeLaundryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeLaundryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeLaundryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeLaundryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        ServiceService service = DepedencyInjector.getInstance(ServiceService.class);
        OrderService orderService = DepedencyInjector.getInstance(OrderService.class);

        ServicePanelView servicePanel = new ServicePanelView();
        OrderPanelView orderPanel = new OrderPanelView();
        IncomePanelView incomePanel = new IncomePanelView();

        new OrderController(orderPanel, orderService);
        new ServiceController(servicePanel, service);
        new IncomeController(incomePanel, orderService);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            HomeLaundryFrame frame = new HomeLaundryFrame(
                    orderPanel, servicePanel, incomePanel
            );

            frame.pack();
            frame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane menuTab;
    private javax.swing.JButton orderMenuButton;
    private javax.swing.JButton reportMenuButton;
    private javax.swing.JButton serviceMenuButton;
    // End of variables declaration//GEN-END:variables
}
